dert werden kann. Die Apostrophe werden in der Ausgabezeichenfolge nicht angezeigt.

Der Standardformatbezeichner "O" oder "o" (und die benutzerdefinierte Formatzeichenfolge "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK") nutzt die drei Möglichkeiten von ISO 8601 zur Darstellung von Zeitzoneninformationen, um die Kind-Eigenschaft der DateTime-Werte beizubehalten:

    Die Zeitzonenkomponente von Datums- und Uhrzeitwerten von DateTimeKind.Local ist die UTC-Abweichung (z. B. +01:00, -07:00). Alle DateTimeOffset-Werte werden ebenfalls in diesem Format dargestellt.

    Die Zeitzonenkomponente von Datums- und Uhrzeitwerten von DateTimeKind.Utc verwenden "Z" (entspricht der Abweichung 0), um UTC darzustellen.

    Datums- und Uhrzeitwerte von DateTimeKind.Unspecified umfassen keine Zeitzoneninformationen.

Da der Standardformatbezeichner "O" oder "o" einem internationalen Standard entspricht, werden bei der Formatierung oder Analyse mit diesem Bezeichner immer die invariante Kultur und der gregorianische Kalender verwendet.

Zeichenfolgen zur Übergabe an die Parse-, TryParse-, ParseExact- und TryParseExact-Methoden von DateTime und DateTimeOffset können mithilfe der Formatbezeichner "O" oder "o" analysiert werden, wenn sie in einem dieser Formate vorliegen. Im Fall von DateTime-Objekten sollte die aufgerufene Analyseüberladung außerdem einen styles-Parameter mit dem Wert "DateTimeStyles.RoundtripKind" enthalten. Beachten Sie, dass Sie nicht die gleichen Ergebnisse wie für "O" oder "o" erhalten, wenn Sie eine Analysemethode mit der benutzerdefinierten Formatzeichenfolge aufrufen, die dem Formatbezeichner "O" oder "o" entspricht. Dafür gibt es folgenden Grund: Analysemethoden, die eine Zeichenfolge mit benutzerdefiniertem Format verwenden, können die Zeichenfolgendarstellung von Datums- und Uhrzeitwerten nicht analysieren, denen die Zeitzonenkomponente fehlt oder die "Z" zur Angabe von UTC verwenden.Sekunde (1–2 Stellen)�Der benutzerdefinierte Formatbezeichner "s" repräsentiert die Sekunden als eine Zahl zwischen 0 und 59. Das Ergebnis steht für ganze Sekunden, die seit der letzten Minute vergangen sind. Ein einstelliger Sekundenwert wird ohne führende Null formatiert.

Bei Verwendung des Formatbezeichners "s" ohne weitere benutzerdefinierte Formatbezeichner wird er als Standardformatbezeichner "s" für Datum und Uhrzeit interpretiert.Sekunde (2 Stellen)�Der benutzerdefinierte Formatbezeichner "ss" (plus beliebig viele zusätzliche s-Bezeichner) repräsentiert die Sekunden als eine Zahl zwischen 00 und 59. Das Ergebnis steht für ganze Sekunden, die seit der letzten Minute vergangen sind. Ein einstelliger Sekundenwert wird mit einer führenden Null formatiert.Kurzes Datumsformat�Der Standardformatbezeichner "d" repräsentiert eine benutzerdefinierte Datums- und Uhrzeitformatzeichenfolge, die durch die DateTimeFormatInfo.ShortDatePattern-Eigenschaft einer bestimmten Kultur definiert wird. Die von der ShortDatePattern-Eigenschaft der invarianten Kultur zurückgegebene benutzerdefinierte Formatzeichenfolge lautet beispielsweise "MM/dd/yyyy".Kurzes Uhrzeitformat�Der Standardformatbezeichner "t" repräsentiert eine benutzerdefinierte Datums- und Uhrzeitformatzeichenfolge, die durch die aktuelle DateTimeFormatInfo.ShortTimePattern-Eigenschaft definiert ist. Die benutzerdefinierte Formatzeichenfolge für die invariante Kultur l