ten konsistent in aufsteigender oder absteigender Reihenfolge sortiert werden. Obwohl der Standardformatbezeichner "s" einen Datums- und Uhrzeitwert in einem konsistenten Format repräsentiert, wird der Wert des zu formatierenden Objekts für Datum und Uhrzeit bei der Formatierung nicht geändert, um die zugehörige DateTime.Kind-Eigenschaft oder den zugehörigen DateTimeOffset.Offset-Wert widerzuspiegeln. Beispielsweise sind die Ergebniszeichenfolgen, die bei Formatierung der Datums- und Uhrzeitwerte 2014-11-15T18:32:17+00:00 und 2014-11-15T18:32:17+08:00 generiert werden, identisch.

Bei Verwendung dieses Standardformatbezeichners wird zur Formatierung oder Analyse immer die invariante Kultur verwendet.statischer KonstruktorStruktur#'"symbol" kann kein Namespace sein.{0} "{1}" von {2} "{3}"Zeittrennzeichen�
Der benutzerdefinierte Formatbezeichner ":" repräsentiert das Zeittrennzeichen, das zur Unterscheidung von Stunden, Minuten und Sekunden verwendet wird. Das geeignete lokalisierte Zeittrennzeichen wird aus der DateTimeFormatInfo.TimeSeparator-Eigenschaft der aktuellen oder angegebenen Kultur abgerufen.

Hinweis: Um das Zeittrennzeichen für eine bestimmte Datums- und Uhrzeitzeichenfolge zu ändern, geben Sie das Trennzeichen innerhalb eines Trennzeichens einer Literalzeichenfolge an. Beispielsweise erzeugt die benutzerdefinierte Formatzeichenfolge "hh'_'dd'_'ss" eine Ergebniszeichenfolge, in der stets "_" (ein Unterstrich) als Zeittrennzeichen verwendet wird. Um das Zeittrennzeichen für alle Datumswerte für eine Kultur zu ändern, ändern Sie entweder den Wert der DateTimeFormatInfo.TimeSeparator-Eigenschaft der aktuellen Kultur, oder instanziieren Sie ein DateTimeFormatInfo-Objekt, weisen Sie das Zeichen der zugehörigen TimeSeparator-Eigenschaft zu, und rufen Sie eine Überladung der Formatierungsmethode auf, die einen IFormatProvider-Parameter umfasst.

Bei Verwendung des Formatbezeichners ":" ohne weitere benutzerdefinierte Formatbezeichner wird er als Standardformatbezeichner für Datums- und Uhrzeitwerte interpretiert und löst eine FormatException aus.Zeitzone�
Der benutzerdefinierte Formatbezeichner "K" repräsentiert die Zeitzoneninformation eines Datums- und Uhrzeitwerts. Bei Verwendung dieses Formatbezeichners mit DateTime-Werten wird die Ergebniszeichenfolge durch den Wert der DateTime.Kind-Eigenschaft definiert:

    Für die lokale Zeitzone (ein DateTime.Kind-Eigenschaftswert von DateTimeKind.Local) entspricht dieser Bezeichner dem Bezeichner "zzz" und erzeugt eine Ergebniszeichenfolge, die die lokale Abweichung von der koordinierten Weltzeit (UTC) enthält, z. B. "-07:00".

    Für eine UTC-Zeit (ein DateTime.Kind-Eigenschaftswert von DateTimeKind.Utc) enthält die Ergebniszeichenfolge ein Zeichen "Z" zur Darstellung eines UTC-Datums.

    Für einen Zeitwert einer nicht angegebenen Zeitzone (ein Zeitwert, dessen DateTime.Kind-Eigenschaft "DateTimeKind.Unspecified" lautet) ist das Ergebnis äquivalent zu "String.Empty".

Für DateTimeOffset-Werte ist der Formatbezeichner "K" äquivalent zum Formatbezeichner "zzz" und erzeugt eine Ergebniszeichenfolge, die das Offset des DateTimeOffset-Werts von UTC enthält.

Bei Verwendung des Formatbezeichners "K" ohne weitere benutzerdefinierte Formatbezeichner wird er als Standardformatbezeichner für Datums- und Uhrzeitwerte interpretiert und löst eine FormatException aus.TypTypeinschränkungTypparameter-Universelle(s) vollständige(s) Datum/Uhrzeit�Der Standardformatbezeichner "U" repräsentiert eine benutzerdefinierte Datums- und Uhrzeitformatzeichenfolge, die durch die DateTimeFormatInfo.FullDateTimePattern-Eigenschaft einer angegebenen Kultur definiert ist. Das Muster ist mit dem F-Muster identisch. Der DateTime-Wert wird jedoch automatisch in UTC konvertiert, bevor er formatiert wird.+Universelle(s) sortierbare(s) Datum/Uhrzeit�Der Standardformatbezeichner "u" repräsentiert eine benutzerdefinierte Datums- und Uhrzeitformatzeichenfolge, die durch die DateTimeFormatInfo.UniversalSortableDateTimePattern-Eigenschaft definiert ist. Das Muster folgt einem definierten Standard, und die Eigenschaft ist schreibgeschützt. Daher ist sie immer gleich, unabhängig von der verwendeten Kultur oder dem angegebenen Formatanbieter. Die benutzerdefinierte Formatzeichenfolge lautet "yyyy'-'MM'-'dd HH':'mm':'ss'Z'". Bei Verwendung dieses Standardformatbezeichners wird bei Formatierung oder Analyse immer die invariante Kultur verwendet.

Obwohl die Ergebniszeichenfolge einen Zeitwert als koordinierte Weltzeit (UTC) ausdrücken sollte, findet während der Formatierung keine Konvertierung des ursprünglichen DateTime-Werts statt. Deshalb müssen Sie einen DateTime-Wert vor der Formatierung durch Aufruf der DateTime.ToUniversalTime-Methode in UTC konvertieren.7Verwendungen in enthaltenden Members wird aktualisiert.9Verwendungen im enthaltenden Projekt werden aktualisiert..Verwendungen im enthaltenden Typ aktualisieren:Verwendungen in abhängigen Projekten werden aktualisiert.%UTC-Abweichung in Stunden und Minuten�Bei DateTime-Werten repräsentiert der benutzerdefinierte Formatbezeichner "zzz" die Abweichung (einschließlich Vorzeichen) der Zeitzone des lokalen Betriebssystems von der koordinierten Weltzeit (UTC), gemessen in Stunden und Minuten. Er spiegelt nicht den Wert einer Instanz der DateTime.Kind-Eigenschaft wider. Aus diesem Grund wird der Formatbezeichner "zzz" nicht zur Verwendung mit DateTime-Werten empfohlen.

Bei DateTimeOffset-Werten stellt dieser Formatbezeichner die Abweichung des DateTimeOffset-Wertes von UTC in Stunden und Minuten dar.

Die Abweichung wird immer mit einem Vorzeichen angezeigt. Ein Pluszeichen (+) steht für Stunden vor UTC, ein Minuszeichen (-) für Stunden nach UTC. Eine einstellige Abweichung wird mit einer führenden Null formatiert.*UTC-Abweichung in Stunden (1–2 Stellen)�Bei DateTime-Werten repräsentiert der benutzerdefinierte Formatbezeichner "z" die Abweichung (einschließlich Vorzeichen) der Zeitzone des lokalen Betriebssystems von der koordinierten Weltzeit (UTC), gemessen in Stunden. Er spiegelt nicht den Wert einer Instanz der DateTime.Kind-Eigenschaft wider. Aus diesem Grund wird der Formatbezeichner "z" nicht zur Verwendung mit DateTime-Werten empfohlen.

Bei DateTimeOffset-Werten stellt dieser Formatbezeichner die Abweichung des DateTimeOffset-Wertes von UTC in Stunden dar.

Die Abweichung wird immer mit eine