namespace Plumb5.Areas.SegmentBuilder.Models
{
    public enum P5SqlComparison
    {
        Equals,
        NotEquals,
        Like,
        NotLike,
        GreaterThan,
        GreaterOrEquals,
        LessThan,
        LessOrEquals,
        In,
        IsNotEmpty,
        IsEmpty,
        CountEquals,
        CountGreaterThan,
        CountLessThan,
        CountNotEquals,
        AverageEquals,
        AverageGreaterThan,
        AverageLessThan,
        AverageNotEquals,
        TotalEquals,
        TotalGreaterThan,
        TotalLessThan,
        TotalNotEquals
    }
}
