D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\appsettings.Development.json
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.staticwebassets.runtime.json
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.exe
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.deps.json
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.runtimeconfig.json
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\AWSSDK.CloudWatch.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\AWSSDK.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Azure.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Azure.Identity.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\BouncyCastle.Cryptography.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Dapper.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\DocumentFormat.OpenXml.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\DocumentFormat.OpenXml.Framework.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Enums.NET.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ExcelDataReader.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ExcelDataReader.DataSet.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ExtendedNumerics.BigDecimal.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\FirebaseAdmin.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Api.Gax.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Api.Gax.Rest.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.Auth.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Humanizer.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Ionic.Zip.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\MathNet.Numerics.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Net.Http.Formatting.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Web.Http.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Web.Http.WebHost.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.AspNetCore.Razor.Language.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Bcl.AsyncInterfaces.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Build.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Build.Framework.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.AnalyzerUtilities.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.CSharp.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.CSharp.Features.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.CSharp.Workspaces.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.Elfie.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.Features.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.Razor.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.Scripting.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.CodeAnalysis.Workspaces.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Data.SqlClient.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.DiaSymReader.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.DotNet.Scaffolding.Shared.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Extensions.DependencyModel.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Identity.Client.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.Identity.Client.Extensions.Msal.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.Abstractions.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.JsonWebTokens.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.Logging.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.Protocols.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IdentityModel.Tokens.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.IO.RecyclableMemoryStream.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.NET.StringTools.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.SqlServer.Server.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.VisualStudio.Web.CodeGeneration.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Microsoft.VisualStudio.Web.CodeGeneration.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\dotnet-aspnet-codegenerator-design.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin