olver.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.Frameworks.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.LibraryModel.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.Packaging.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.ProjectModel.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.Protocol.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\NuGet.Versioning.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\BouncyCastle.Crypto.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ICSharpCode.SharpZipLib.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\SixLabors.Fonts.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\SixLabors.ImageSharp.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.CodeDom.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Composition.AttributedModel.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Composition.Convention.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Composition.Hosting.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Composition.Runtime.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Composition.TypedParts.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Configuration.ConfigurationManager.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Data.OleDb.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\System.Diagnostics.PerformanceCounter.dll
D:\P5_Core_7\MailBran