inBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.Features.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.Scripting.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\cs\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pl\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\tr\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.CodeAnalysis.Workspaces.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\de\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\es\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\fr\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\it\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ja\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ko\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\pt-BR\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\ru\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hans\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\zh-Hant\Microsoft.Data.SqlClient.resources.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\unix\lib\net8.0\Microsoft.Data.SqlClient.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\Microsoft.Data.SqlClient.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win-arm\native\Microsoft.Data.SqlClient.SNI.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win-arm64\native\Microsoft.Data.SqlClient.SNI.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\Microsoft.Win32.SystemEvents.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Data.OleDb.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Diagnostics.PerformanceCounter.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Management.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Runtime.Caching.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\runtimes\win\lib\net8.0\System.ServiceProcess.ServiceController.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\AWSSDK.CloudFront.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Bdev.Net.Dns.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\DBInteraction.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Facebook.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Ads.Gax.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Ads.GoogleAds.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Ads.GoogleAds.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Api.Gax.Grpc.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.Auth.PlatformServices.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.PlatformServices.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Apis.Sheets.v4.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Google.Protobuf.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Grpc.Core.Api.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\HtmlAgilityPack.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\IP5GenralDL.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\P5GenralDL.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\P5GenralML.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5GenralFunction.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Renci.SshNet.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\RestSharp.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\StackExchange.Redis.StrongName.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\PushSharp.Apple.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\PushSharp.Core.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\AWSSDK.S3.dll
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\DBInteraction.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\P5GenralDL.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\P5GenralML.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\Plumb5GenralFunction.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\bin\Debug\net8.0\IP5GenralDL.pdb
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\obj\Debug\net8.0\Plumb5.csproj.AssemblyReference.cache
D:\P5_Core_7\MailBranch_UI_Core\Plumb5MainBuild\Plumb5\obj\Debug\net8.0\Plumb5.GeneratedMSBuildEditorConfig.edit