name: My .NET Action

on:
  push:
    branches: [ master ]

jobs:
  stop-iis-service:
    runs-on: [windows-2019]
    env:
      server: '103.146.242.243'
      cert-path: './server-cert'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: IIS stop
        # You may also reference the major or major.minor version
        uses: im-open/iis-service-action@v1.0.7
        with:
         action: 'stop'
         server: ${{ env.server }}
         service-account-id: 'Administrator'
         service-account-password: 'e7ntA#zN5x2Brk'
