name: Stop IIS Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stop-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Make an API call
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://pgtrack.plumb5.com/VisitorDetail/InitiateTrackDetail'
       method: 'POST'
       
          
    - name: Stop IIS Website via SSH
      uses: appleboy/ssh-action@master
      with:
        host: '103.146.242.243'
        username: 'Administrator'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          powershell -Command "Import-Module WebAdministration; Stop-Website -Name 'github'
