on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - name: Build solution
      run: dotnet build -c Release --verbosity minimal
      
    - name: Run tests
      run: dotnet test -c Release --verbosity minimal --no-build --no-restore
      
    - name: Publish
      run: dotnet publish -c Release --no-build --no-restore

    - name: SFTP-Deploy-Action        
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          
          
          # Path for specific folder on server for files deployment
          local-path: /home/runner/work/CoreGithub/CoreGithub/CoreGithub/bin/Release/net8.0/publish/
          remote-path: /
          # sync: "full"
          # Port for SFTP access to server
          remote-port: 22
    
