name: Stop IIS Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stop-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Make an API call
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://reqbin.com/echo/post/json'
       method: 'POST'
       customHeaders: '{"Content-Type": "application/json"}'
       data: '{  "Id": 78912,  "Customer": "Jason Sweet",  "Quantity": 1,  "Price": 18.00}'
          
   
