name: Stop IIS Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stop-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Stop IIS Website via SSH
      uses: appleboy/ssh-action@master
      with:
        host: '103.146.242.243'
        username: 'Administrator'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          powershell -Command "Import-Module WebAdministration; Stop-Website -Name 'github'
