name: Stop IIS Website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  stop-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /
        remote: pub
        host: '103.146.242.243'
        username: 'Administrator'
        password: 'e7ntA#zN5x2Brk'
