name: Publish to Beta
on:
  push:
    branches:
      - master
jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Logging
      run: |
       echo "${{github.event.commits[0].message}}"
      
    - name: Stop AppPool
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://iis.plumb5.in/?actiontype=stop&site=GitHubPublish'
       method: 'GET'
       customHeaders: '{"Content-Type": "application/json"}'
