name: Publish plumb5 asset
on:
  push:
    branches:
      - master
      
  #schedule: ## Schedule the job to run at 12.am daily.
    #- cron: '45 19 * * *'
jobs:
  upload_files:
    runs-on: ubuntu-latest      
   
    if : ${{ github.event.commits[0].message == 'asset' }}
    name: Upload a builded file.
    steps:  
    
    - name: Stop AppPool
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://iis.plumb5.in/?actiontype=stop&site=GitHubPublish'
       method: 'GET'
       customHeaders: '{"Content-Type": "application/json"}'
       
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        port: 22
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localPath: './Plumb5/wwwroot/Content/css/'
        remotePath: './wwwroot/Content/css/'
        additionalPaths: '{"./Plumb5/wwwroot/js/":"./wwwroot/js/"}' 
       

    - name: Start AppPool
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://iis.plumb5.in/?actiontype=start&site=GitHubPublish'
       method: 'GET'
       customHeaders: '{"Content-Type": "application/json"}'
