name: Publish plumb5
on:
  push:
    branches:
      - master
jobs:
  upload_files:
    runs-on: ubuntu-latest       
    
    if : ${{ github.event.commits[0].message == 'plumb5' }}
    name: Upload a builded file.
    steps:  
    - name: Logging
      run: echo "Msg:${{github.event.commits[0].message}}"
       
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - name: Build solution
      run: dotnet build -c Release --verbosity minimal /home/runner/work/CoreGithub/CoreGithub/Plumb5/Plumb5.csproj
      
    - name: Run tests
      run: dotnet test -c Release --verbosity minimal --no-build --no-restore /home/runner/work/CoreGithub/CoreGithub/Plumb5/Plumb5.csproj
      
    - name: Publish
      run: dotnet publish -c Release --no-build --no-restore /home/runner/work/CoreGithub/CoreGithub/Plumb5/Plumb5.csproj

    - name: Stop AppPool
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://iis.plumb5.in/?actiontype=stop&site=GitHubPublish'
       method: 'GET'
       customHeaders: '{"Content-Type": "application/json"}'
       
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        port: 22
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localPath: '/home/runner/work/CoreGithub/CoreGithub/Plumb5/bin/Release/net8.0/Plumb5.dll'
        remotePath: './'

    - name: Start AppPool
      uses: fjogeleit/http-request-action@v1
      with:
       url: 'https://iis.plumb5.in/?actiontype=start&site=GitHubPublish'
       method: 'GET'
       customHeaders: '{"Content-Type": "application/json"}'
