name: Publish plumb5
on:
  push:
    branches:
      - master
jobs:
  upload_files:
    runs-on: ubuntu-latest      
   
    name: Upload a builded file.
    steps:  
  
    - name: Checkout
      uses: actions/checkout@v2.3.4
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
     
    - name: Publish
      run: dotnet publish -c Release --no-build --no-restore /home/runner/work/CoreGithub/CoreGithub/Plumb5/Plumb5.csproj
   
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.FTP_HOST }}
        port: 22
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localPath: '/home/runner/work/CoreGithub/CoreGithub/Plumb5/bin/Release/net8.0/publish/appsettings.json'
        remotePath: './deploy-test'
