name: Sftp Publish 

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution
        run: dotnet build -c Release --verbosity minimal

      - name: Run tests
        run: dotnet test -c Release --verbosity minimal --no-build --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build --no-restore

      - name: Upload Core artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Core
          path: /home/runner/work/CoreGithub/CoreGithub/CoreGithub/bin/Release/net8.0/publish/


        
     
