name: Sftp Publish 

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution
        run: dotnet build -c Release --verbosity minimal

      - name: Run tests
        run: dotnet test -c Release --verbosity minimal --no-build --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build --no-restore

      - name: Upload Core artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Core
          path: /home/runner/work/CoreGithub/CoreGithub/CoreGithub/bin/Release/net8.0/publish/


  deploy_core:
      name: Deploy Core
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Core  

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: master
          
      - name: SFTP-Deploy-Action        
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          
          
          # Path for specific folder on server for files deployment
          remote-path: /deploy-test

          # Port for SFTP access to server
          remote-port: 22

