name: Sftp Publish 

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:    
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: SFTP-Deploy-Action        
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          
          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          
          
          # Path for specific folder on server for files deployment
          local-path: ./Plumb5/wwwroot/js
          remote-path: ./wwwroot/js
          # sync: "full"
          # Port for SFTP access to server
          remote-port: 22

